# Generated by Django 3.1 on 2020-08-21 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capital_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('isin', models.CharField(default='', max_length=20)),
                ('status', models.CharField(choices=[('a', 'Activo'), ('n', 'No activo')], default='a', max_length=1)),
                ('sector', models.CharField(choices=[('auto', 'Automoción'), ('salud', 'Salud'), ('elect', 'Energía'), ('tecno', 'Tecnología'), ('bienes', 'Bienes de consumo'), ('otros', 'Otros')], default='otros', max_length=10)),
                ('pais', models.CharField(choices=[('spain', 'España'), ('united states', 'EEUU'), ('others', 'Otros')], default='spain', max_length=20)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha alta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('c', 'Compra'), ('v', 'Venta')], default='c', max_length=1)),
                ('acciones', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cambio_moneda', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micartera.cartera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micartera.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalesEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_bursatil', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('beta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('num_acciones', models.IntegerField(default=0)),
                ('proximos_resultados', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micartera.empresa')),
            ],
        ),
    ]
