# Generated by Django 3.0 on 2020-07-07 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='isin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('spain', 'España'), ('united states', 'EEUU')], default='spain', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
