# Generated by Django 3.0 on 2020-07-07 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0002_auto_20200707_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
