# Generated by Django 4.0 on 2022-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0003_alter_empresa_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mercado',
            field=models.CharField(choices=[('NYSE', 'NYSE'), ('NASDAQ', 'NASDAQ'), ('others', 'Otros')], default='otros', max_length=10),
        ),
    ]
