# Generated by Django 3.0 on 2020-07-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0003_auto_20200707_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micartera.Cartera'),
        ),
    ]
