# Generated by Django 3.1 on 2020-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0004_auto_20200707_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartera',
            name='cash_balance',
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('a', 'Acción'), ('etf', 'ETF'), ('otros', 'Otros')], default='a', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartera',
            name='capital_inicial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(choices=[('spain', 'España'), ('united states', 'EEUU'), ('others', 'Otros')], default='spain', max_length=20),
        ),
    ]
