# Generated by Django 4.0 on 2022-04-11 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0004_empresa_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCasillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('casilla', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('a', 'Acción'), ('crypto', 'Crypto'), ('etf', 'ETF'), ('otros', 'Otros')], default='a', max_length=10),
        ),
    ]
