# Generated by Django 4.0 on 2022-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0005_historicocasillas_alter_empresa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocasillas',
            name='hblocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicocasillas',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
