# Generated by Django 4.0 on 2022-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0006_historicocasillas_hblocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoempresa',
            name='capitalExpenditures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='cashflowFromFinancing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='cashflowFromInvestment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='longTermDebt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='operatingCashflow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='paymentsForRepurchaseOfCommonStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='shortTermDebt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='totalCurrentAssets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='totalCurrentLiabilities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='totalNonCurrentAssets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoempresa',
            name='totalNonCurrentLiabilities',
            field=models.IntegerField(default=0),
        ),
    ]
