# Generated by Django 3.2.10 on 2022-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0009_auto_20220420_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='qhistoricoempresa',
            name='netIncome',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='qhistoricoempresa',
            name='reportedDate',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qhistoricoempresa',
            name='totalRevenue',
            field=models.FloatField(default=0),
        ),
    ]
