# Generated by Django 3.2.10 on 2022-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0010_auto_20220420_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='qhistoricoempresa',
            name='confirmado',
            field=models.BooleanField(default=True),
        ),
    ]
