# Generated by Django 3.2.10 on 2022-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0011_qhistoricoempresa_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='qhistoricoempresa',
            name='estimatedTotalRevenue',
            field=models.FloatField(default=0),
        ),
    ]
