# Generated by Django 3.2.10 on 2022-04-22 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0013_qhistoricoempresa_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cripto',
            name='marketcap',
        ),
        migrations.RemoveField(
            model_name='cripto',
            name='precio',
        ),
        migrations.AddField(
            model_name='cripto',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cripto',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cripto',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cripto',
            name='logo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cripto',
            name='technical_doc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='FundamentalesCripto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(blank=True, default=datetime.datetime.now)),
                ('cmc_rank', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('marketcap', models.FloatField(default=0)),
                ('tags', models.CharField(max_length=100)),
                ('max_supply', models.FloatField(default=0)),
                ('total_supply', models.FloatField(default=0)),
                ('cripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micartera.cripto')),
            ],
        ),
    ]
