# Generated by Django 4.0.3 on 2022-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0014_auto_20220422_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalescripto',
            name='market_cap_dominance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundamentalescripto',
            name='percent_change_24h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundamentalescripto',
            name='percent_change_30d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundamentalescripto',
            name='percent_change_60d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundamentalescripto',
            name='percent_change_7d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundamentalescripto',
            name='percent_change_90d',
            field=models.FloatField(default=0),
        ),
    ]
