# Generated by Django 4.0.3 on 2022-04-22 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0015_fundamentalescripto_market_cap_dominance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCripto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(blank=True, default=datetime.datetime.now)),
                ('porc_ballenas', models.FloatField(default=0)),
                ('mineria', models.TextField(default='', max_length=500)),
                ('roadmap', models.TextField(default='', max_length=500)),
                ('proyeccion', models.TextField(default='', max_length=500)),
                ('cripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micartera.cripto')),
            ],
        ),
    ]
