# Generated by Django 3.2.10 on 2022-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0016_analisiscripto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='industria',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sic',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sicIndustry',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sicSector',
            field=models.CharField(default='', max_length=80),
        ),
    ]
