# Generated by Django 4.0.3 on 2022-05-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0018_movimiento_comision_movimiento_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBX'), ('JPY', 'JPY'), ('otra', 'Otra')], default='usd', max_length=10),
        ),
    ]
