# Generated by Django 4.0.3 on 2022-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0019_alter_movimiento_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('CASH IN', 'Ingreso'), ('CASH OUT', 'Retirada')], default='compra', max_length=10),
        ),
    ]
