# Generated by Django 4.0.3 on 2022-05-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micartera', '0020_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCartera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micartera.cartera')),
            ],
        ),
    ]
